In [10]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer , SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('titanic.csv',usecols=['Age','Fare','Pclass','Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [4]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [11]:
X = df.drop(columns='Survived')
y=df['Survived']

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=2)
X_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [17]:
knn = KNNImputer() # weights='uniform' by default

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [7]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

     Pclass   Age      Fare
0       1.0  40.0   27.7208
1       3.0   4.0   16.7000
2       3.0  47.0    9.0000
3       3.0   9.0   31.3875
4       3.0  20.0    9.8458
..      ...   ...       ...
707     3.0  30.0    8.6625
708     3.0  24.4    8.7125
709     1.0  71.0   49.5042
710     1.0  33.6  221.7792
711     1.0  42.8   25.9250

[712 rows x 3 columns]

In [13]:
lr = LogisticRegression()

lr.fit(X_train_trf , y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_pred,y_test)

0.7039106145251397

In [19]:
# Comparison with SimpleImputer --> Mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [20]:
lr = LogisticRegression()

lr.fit(X_train_trf2 , y_train)

y_pred = lr.predict(X_test_trf2)

accuracy_score(y_pred,y_test)

0.6927374301675978

In [16]:
knn = KNNImputer(weights='distance')

X_train_trf3 = knn.fit_transform(X_train)
X_test_trf3 = knn.transform(X_test)

In [18]:
lr = LogisticRegression()

lr.fit(X_train_trf3 , y_train)

y_pred = lr.predict(X_test_trf3)

accuracy_score(y_pred,y_test)

0.7094972067039106