In [1]:
import pandas as pd

### Working with JSON

In [2]:
pd.read_json('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day16%20-%20working-with-json-and-sql/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.6740
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.8670
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,3.8600
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,2.5100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.1710
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.1920
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-03,1783036801,0.2820

### Working with SQL

In [7]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 1.2 MB/s eta 0:00:14
   - -------------------------------------- 0.8/17.7 MB 1.0 MB/s eta 0:00:17
   - -------------------------------------- 0.8/17.7 MB 1.0 MB/s eta 0:00:17
   -- ------------------------------------- 1.0/17.7 MB 949.4 kB/s eta 0:00:18
   -- ------------------------------------- 1.0/17.7 MB 949.4 kB/s eta 0:00:18
   -- ------------------------------------- 1.0/17.7 MB 949.4 kB/s eta 0:00:18
   -- ------------------------------------- 1.3/17.7 MB 681.4 kB/s eta 0:00:25
   -- ------------------------------------- 1.3/17.7 MB 681.4 kB/s eta 0:00:25
   -- ------------------------------------- 1.3/17.7 MB 681.4 kB/s eta 0:00:25
   -- ------------------------------------- 1.3/17.7 MB 681.4 kB/s eta 0:00:25
   --- ------------------------------------ 1.6/17.7 MB 579.2 kB/s eta 0:00:28
   --- ------------------------------------ 1.6/17.7 MB 579.2 kB/s eta 0:00:28
   --- ------------------------------------ 1.6/17.7 MB 579.2 kB/s eta 0:00:28
   --- ------------------------------------ 1.6/17.7 MB 579.2 kB/s eta 0:00:28
   ---- ----------------------------------- 1.8/17.7 MB 491.2 kB/s eta 0:00:33
   ---- ----------------------------------- 1.8/17.7 MB 491.2 kB/s eta 0:00:33
   ---- ----------------------------------- 1.8/17.7 MB 491.2 kB/s eta 0:00:33
   ---- ----------------------------------- 1.8/17.7 MB 491.2 kB/s eta 0:00:33
   ---- ----------------------------------- 1.8/17.7 MB 491.2 kB/s eta 0:00:33
   ---- ----------------------------------- 2.1/17.7 MB 446.7 kB/s eta 0:00:35
   ---- ----------------------------------- 2.1/17.7 MB 446.7 kB/s eta 0:00:35
   ---- ----------------------------------- 2.1/17.7 MB 446.7 kB/s eta 0:00:35
   ---- ----------------------------------- 2.1/17.7 MB 446.7 kB/s eta 0:00:35
   ----- ---------------------------------- 2.4/17.7 MB 417.1 kB/s eta 0:00:37
   ----- ---------------------------------- 2.4/17.7 MB 417.1 kB/s eta 0:00:37
   ----- ---------------------------------- 2.4/17.7 MB 417.1 kB/s eta 0:00:37
   ----- ---------------------------------- 2.4/17.7 MB 417.1 kB/s eta 0:00:37
   ----- ---------------------------------- 2.6/17.7 MB 395.3 kB/s eta 0:00:39
   ----- ---------------------------------- 2.6/17.7 MB 395.3 kB/s eta 0:00:39
   ----- ---------------------------------- 2.6/17.7 MB 395.3 kB/s eta 0:00:39
   ----- ---------------------------------- 2.6/17.7 MB 395.3 kB/s eta 0:00:39
   ----- ---------------------------------- 2.6/17.7 MB 395.3 kB/s eta 0:00:39
   ----- ---------------------------------- 2.6/17.7 MB 395.3 kB/s eta 0:00:39
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------ --------------------------------- 2.9/17.7 MB 369.6 kB/s eta 0:00:41
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.1/17.7 MB 334.2 kB/s eta 0:00:44
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   ------- -------------------------------- 3.4/17.7 MB 306.4 kB/s eta 0:00:47
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.7/17.7 MB 267.5 kB/s eta 0:00:53
   -------- ------------------------------- 3.9/17.7 MB 256.8 kB/s eta 0:00:54
   -------- ------------------------------- 3.9/17.7 MB 256.8 kB/s eta 0:00:54
   -------- ------------------------------- 3.9/17.7 MB 256.8 kB/s eta 0:00:54
   -------- ------------------------------- 3.9/17.7 MB 256.8 kB/s eta 0:00:54
   -------- ------------------------------- 3.9/17.7 MB 256.8 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   --------- ------------------------------ 4.2/17.7 MB 253.2 kB/s eta 0:00:54
   ---------- ----------------------------- 4.5/17.7 MB 248.7 kB/s eta 0:00:54
   ---------- ----------------------------- 4.5/17.7 MB 248.7 kB/s eta 0:00:54
   ---------- ----------------------------- 4.5/17.7 MB 248.7 kB/s eta 0:00:54
   ---------- ----------------------------- 4.5/17.7 MB 248.7 kB/s eta 0:00:54
   ---------- ----------------------------- 4.7/17.7 MB 250.6 kB/s eta 0:00:52
   ---------- ----------------------------- 4.7/17.7 MB 250.6 kB/s eta 0:00:52
   ---------- ----------------------------- 4.7/17.7 MB 250.6 kB/s eta 0:00:52
   ---------- ----------------------------- 4.7/17.7 MB 250.6 kB/s eta 0:00:52
   ---------- ----------------------------- 4.7/17.7 MB 250.6 kB/s eta 0:00:52
   ----------- ---------------------------- 5.0/17.7 MB 251.0 kB/s eta 0:00:51
   ----------- ---------------------------- 5.0/17.7 MB 251.0 kB/s eta 0:00:51
   ----------- ---------------------------- 5.0/17.7 MB 251.0 kB/s eta 0:00:51
   ----------- ---------------------------- 5.0/17.7 MB 251.0 kB/s eta 0:00:51
   ----------- ---------------------------- 5.2/17.7 MB 253.4 kB/s eta 0:00:50
   ----------- ---------------------------- 5.2/17.7 MB 253.4 kB/s eta 0:00:50
   ----------- ---------------------------- 5.2/17.7 MB 253.4 kB/s eta 0:00:50
   ----------- ---------------------------- 5.2/17.7 MB 253.4 kB/s eta 0:00:50
   ------------ --------------------------- 5.5/17.7 MB 255.1 kB/s eta 0:00:48
   ------------ --------------------------- 5.5/17.7 MB 255.1 kB/s eta 0:00:48
   ------------ --------------------------- 5.5/17.7 MB 255.1 kB/s eta 0:00:48
   ------------- -------------------------- 5.8/17.7 MB 260.0 kB/s eta 0:00:46
   ------------- -------------------------- 5.8/17.7 MB 260.0 kB/s eta 0:00:46
   ------------- -------------------------- 5.8/17.7 MB 260.0 kB/s eta 0:00:46
   ------------- -------------------------- 6.0/17.7 MB 264.5 kB/s eta 0:00:45
   ------------- -------------------------- 6.0/17.7 MB 264.5 kB/s eta 0:00:45
   -------------- ------------------------- 6.3/17.7 MB 270.2 kB/s eta 0:00:43
   -------------- ------------------------- 6.3/17.7 MB 270.2 kB/s eta 0:00:43
   -------------- ------------------------- 6.3/17.7 MB 270.2 kB/s eta 0:00:43
   -------------- ------------------------- 6.6/17.7 MB 275.7 kB/s eta 0:00:41
   -------------- ------------------------- 6.6/17.7 MB 275.7 kB/s eta 0:00:41
   --------------- ------------------------ 6.8/17.7 MB 281.0 kB/s eta 0:00:39
   --------------- ------------------------ 6.8/17.7 MB 281.0 kB/s eta 0:00:39
   --------------- ------------------------ 6.8/17.7 MB 281.0 kB/s eta 0:00:39
   ---------------- ----------------------- 7.1/17.7 MB 284.6 kB/s eta 0:00:38
   ---------------- ----------------------- 7.1/17.7 MB 284.6 kB/s eta 0:00:38
   ---------------- ----------------------- 7.3/17.7 MB 290.6 kB/s eta 0:00:36
   ---------------- ----------------------- 7.3/17.7 MB 290.6 kB/s eta 0:00:36
   ----------------- ---------------------- 7.6/17.7 MB 296.4 kB/s eta 0:00:35
   ----------------- ---------------------- 7.6/17.7 MB 296.4 kB/s eta 0:00:35
   ----------------- ---------------------- 7.6/17.7 MB 296.4 kB/s eta 0:00:35
   ----------------- ---------------------- 7.9/17.7 MB 299.5 kB/s eta 0:00:33
   ----------------- ---------------------- 7.9/17.7 MB 299.5 kB/s eta 0:00:33
   ------------------ --------------------- 8.1/17.7 MB 303.5 kB/s eta 0:00:32
   ------------------ --------------------- 8.1/17.7 MB 303.5 kB/s eta 0:00:32
   ------------------ --------------------- 8.1/17.7 MB 303.5 kB/s eta 0:00:32
   ------------------ --------------------- 8.4/17.7 MB 307.7 kB/s eta 0:00:31
   ------------------ --------------------- 8.4/17.7 MB 307.7 kB/s eta 0:00:31
   ------------------- -------------------- 8.7/17.7 MB 311.5 kB/s eta 0:00:29
   ------------------- -------------------- 8.7/17.7 MB 311.5 kB/s eta 0:00:29
   -------------------- ------------------- 8.9/17.7 MB 316.4 kB/s eta 0:00:28
   -------------------- ------------------- 8.9/17.7 MB 316.4 kB/s eta 0:00:28
   -------------------- ------------------- 8.9/17.7 MB 316.4 kB/s eta 0:00:28
   -------------------- ------------------- 9.2/17.7 MB 320.0 kB/s eta 0:00:27
   -------------------- ------------------- 9.2/17.7 MB 320.0 kB/s eta 0:00:27
   --------------------- ------------------ 9.4/17.7 MB 323.5 kB/s eta 0:00:26
   --------------------- ------------------ 9.4/17.7 MB 323.5 kB/s eta 0:00:26
   --------------------- ------------------ 9.7/17.7 MB 328.0 kB/s eta 0:00:25
   --------------------- ------------------ 9.7/17.7 MB 328.0 kB/s eta 0:00:25
   ---------------------- ----------------- 10.0/17.7 MB 331.1 kB/s eta 0:00:24
   ---------------------- ----------------- 10.0/17.7 MB 331.1 kB/s eta 0:00:24
   ---------------------- ----------------- 10.0/17.7 MB 331.1 kB/s eta 0:00:24
   ----------------------- ---------------- 10.2/17.7 MB 334.2 kB/s eta 0:00:23
   ----------------------- ---------------- 10.2/17.7 MB 334.2 kB/s eta 0:00:23
   ----------------------- ---------------- 10.2/17.7 MB 334.2 kB/s eta 0:00:23
   ----------------------- ---------------- 10.2/17.7 MB 334.2 kB/s eta 0:00:23
   ----------------------- ---------------- 10.5/17.7 MB 316.5 kB/s eta 0:00:23
   ----------------------- ---------------- 10.5/17.7 MB 316.5 kB/s eta 0:00:23
   ----------------------- ---------------- 10.5/17.7 MB 316.5 kB/s eta 0:00:23
   ------------------------ --------------- 10.7/17.7 MB 317.6 kB/s eta 0:00:22
   ------------------------ --------------- 10.7/17.7 MB 317.6 kB/s eta 0:00:22
   ------------------------ --------------- 10.7/17.7 MB 317.6 kB/s eta 0:00:22
   ------------------------ --------------- 11.0/17.7 MB 317.9 kB/s eta 0:00:21
   ------------------------ --------------- 11.0/17.7 MB 317.9 kB/s eta 0:00:21
   ------------------------ --------------- 11.0/17.7 MB 317.9 kB/s eta 0:00:21
   ------------------------ --------------- 11.0/17.7 MB 317.9 kB/s eta 0:00:21
   ------------------------- -------------- 11.3/17.7 MB 319.1 kB/s eta 0:00:21
   ------------------------- -------------- 11.3/17.7 MB 319.1 kB/s eta 0:00:21
   ------------------------- -------------- 11.3/17.7 MB 319.1 kB/s eta 0:00:21
   -------------------------- ------------- 11.5/17.7 MB 321.9 kB/s eta 0:00:20
   -------------------------- ------------- 11.5/17.7 MB 321.9 kB/s eta 0:00:20
   -------------------------- ------------- 11.5/17.7 MB 321.9 kB/s eta 0:00:20
   -------------------------- ------------- 11.5/17.7 MB 321.9 kB/s eta 0:00:20
   -------------------------- ------------- 11.8/17.7 MB 322.2 kB/s eta 0:00:19
   -------------------------- ------------- 11.8/17.7 MB 322.2 kB/s eta 0:00:19
   -------------------------- ------------- 11.8/17.7 MB 322.2 kB/s eta 0:00:19
   -------------------------- ------------- 11.8/17.7 MB 322.2 kB/s eta 0:00:19
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.1/17.7 MB 323.3 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   --------------------------- ------------ 12.3/17.7 MB 314.7 kB/s eta 0:00:18
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ---------------------------- ----------- 12.6/17.7 MB 319.5 kB/s eta 0:00:16
   ----------------------------- ---------- 12.8/17.7 MB 330.6 kB/s eta 0:00:15
   ----------------------------- ---------- 12.8/17.7 MB 330.6 kB/s eta 0:00:15
   ----------------------------- ---------- 12.8/17.7 MB 330.6 kB/s eta 0:00:15
   ----------------------------- ---------- 12.8/17.7 MB 330.6 kB/s eta 0:00:15
   ----------------------------- ---------- 13.1/17.7 MB 331.4 kB/s eta 0:00:14
   ----------------------------- ---------- 13.1/17.7 MB 331.4 kB/s eta 0:00:14
   ----------------------------- ---------- 13.1/17.7 MB 331.4 kB/s eta 0:00:14
   ------------------------------ --------- 13.4/17.7 MB 333.5 kB/s eta 0:00:13
   ------------------------------ --------- 13.4/17.7 MB 333.5 kB/s eta 0:00:13
   ------------------------------ --------- 13.6/17.7 MB 336.5 kB/s eta 0:00:13
   ------------------------------ --------- 13.6/17.7 MB 336.5 kB/s eta 0:00:13
   ------------------------------- -------- 13.9/17.7 MB 341.8 kB/s eta 0:00:12
   -------------------------------- ------- 14.2/17.7 MB 356.5 kB/s eta 0:00:10
   -------------------------------- ------- 14.4/17.7 MB 363.1 kB/s eta 0:00:09
   -------------------------------- ------- 14.4/17.7 MB 363.1 kB/s eta 0:00:09
   --------------------------------- ------ 14.7/17.7 MB 367.0 kB/s eta 0:00:09
   --------------------------------- ------ 14.7/17.7 MB 367.0 kB/s eta 0:00:09
   --------------------------------- ------ 14.9/17.7 MB 372.1 kB/s eta 0:00:08
   ---------------------------------- ----- 15.2/17.7 MB 377.0 kB/s eta 0:00:07
   ---------------------------------- ----- 15.5/17.7 MB 390.3 kB/s eta 0:00:06
   ---------------------------------- ----- 15.5/17.7 MB 390.3 kB/s eta 0:00:06
   ----------------------------------- ---- 15.7/17.7 MB 395.2 kB/s eta 0:00:05
   ------------------------------------ --- 16.0/17.7 MB 400.0 kB/s eta 0:00:05
   ------------------------------------ --- 16.3/17.7 MB 404.7 kB/s eta 0:00:04
   ------------------------------------ --- 16.3/17.7 MB 404.7 kB/s eta 0:00:04
   ------------------------------------- -- 16.5/17.7 MB 419.0 kB/s eta 0:00:03
   ------------------------------------- -- 16.5/17.7 MB 419.0 kB/s eta 0:00:03
   ------------------------------------- -- 16.8/17.7 MB 420.8 kB/s eta 0:00:03
   ------------------------------------- -- 16.8/17.7 MB 420.8 kB/s eta 0:00:03
   -------------------------------------- - 17.0/17.7 MB 423.7 kB/s eta 0:00:02
   -------------------------------------- - 17.0/17.7 MB 423.7 kB/s eta 0:00:02
   -------------------------------------- - 17.0/17.7 MB 423.7 kB/s eta 0:00:02
   ---------------------------------------  17.3/17.7 MB 429.6 kB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 429.6 kB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 430.9 kB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 437.3 kB/s  0:00:48
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

In [10]:
import mysql.connector

In [12]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [13]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

C:\Users\DELL\AppData\Local\Temp\ipykernel_21252\4272969784.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [14]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]